### ISSUE TITLE
Issue with Testing "qc init --import ../demo.qdpx": ImportError: cannot import name 'SIGWINCH' from 'signal'

### ISSUE THREAD

**Issue by gsalfourn** [cproctor/qualitative-coding#70]
I was trying out the scripts for qc on Windows 11, Python 3.12.

The following lines worked well:

```
cd ~/Desktop
curl -O https://computationalliteracies.net/people/chris/demo.qdpx
mkdir qc_demo
cd qc_demo
```

However, when I ran the line below:

```
qc init --import ../demo.qdpx
```

I got the following error message:

`ImportError: cannot import name 'SIGWINCH' from 'signal'`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\qc.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\qualitative_coding\cli\__init__.py", line 6, in <module>
    from qualitative_coding.cli.codes import codes_group
  File "C:\Python312\Lib\site-packages\qualitative_coding\cli\codes\__init__.py", line 3, in <module>
    from qualitative_coding.cli.codes.stats import stats
  File "C:\Python312\Lib\site-packages\qualitative_coding\cli\codes\stats.py", line 6, in <module>
    from qualitative_coding.views.viewer import QCCorpusViewer
  File "C:\Python312\Lib\site-packages\qualitative_coding\views\viewer.py", line 3, in <module>
    from qualitative_coding.views.coding_ui import CodingUI
  File "C:\Python312\Lib\site-packages\qualitative_coding\views\coding_ui.py", line 3, in <module>
    from signal import signal, SIGWINCH
ImportError: cannot import name 'SIGWINCH' from 'signal' (C:\Python312\Lib\signal.py)
```

**Comment by cproctor** [comment]
Thanks for reporting this issue. I just pushed v1.6.1, which will fix this issue. However, I don't have the capacity to test on Windows so while I'm happy to address bug reports, I can't run comprehensive tests.
