### ISSUE TITLE
Codebook syntax errors should be handled more gracefully

### ISSUE THREAD

**Issue by cproctor** [cproctor/qualitative-coding#72]
Many commands need to read the codebook; which should be in YAML format. However, it's part of the standard workflow to edit the codebook by hand. When the codebook is unparsable, the user gets a python stack trace, as shown below. 

```
% qc codes rename broadening_participation there_were_only_two_females
Traceback (most recent call last):
  File "/Users/chrisp/.local/bin/qc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/qualitative_coding/cli/codes/rename.py", line 24, in rename
    corpus.rename_codes(
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/qualitative_coding/corpus.py", line 824, in rename_codes
    self.update_codebook()
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/qualitative_coding/corpus.py", line 794, in update_codebook
    code_tree = self.get_codebook()
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/qualitative_coding/corpus.py", line 363, in get_codebook
    return TreeNode.read_yaml(self.codebook_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/qualitative_coding/tree_node.py", line 20, in read_yaml
    return TreeNode({cls.root: yaml.safe_load(f)})
                               ^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/chrisp/.local/pipx/venvs/qualitative-coding/lib/python3.12/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "codebook.yaml", line 22, column 21
```

It would be better to catch this error and format it nicely for the user. Something like:
```
Error reading codebook.yaml. 
There is a syntax error on line 22, column 21: mapping values are not allowed here.
```

**Comment by cproctor** [comment]
Done!
